# Generated by Django 4.1.7 on 2023-05-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_name_passenger_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='address',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
