# Generated by Django 4.1.7 on 2023-06-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_passenger_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
